import asyncio
import time
from datetime import datetime
from typing import List

from metaapi_cloud_sdk import MetaApi  # type: ignore

from ficus.mt5.MetatraderStorage import MetatraderSymbolPriceManager
from ficus.mt5.listeners.BitcoinSyncListener import BitcoinSyncListener

# Replace with your MetaAPI token and account ID
META_API_TOKEN = 'eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzZjN2NiNzgwNmIxMWMyNDU5MWQ3YTE4MmZmOWY2OCIsInBlcm1pc3Npb25zIjpbXSwiYWNjZXNzUnVsZXMiOlt7ImlkIjoidHJhZGluZy1hY2NvdW50LW1hbmFnZW1lbnQtYXBpIiwibWV0aG9kcyI6WyJ0cmFkaW5nLWFjY291bnQtbWFuYWdlbWVudC1hcGk6cmVzdDpwdWJsaWM6KjoqIl0sInJvbGVzIjpbInJlYWRlciIsIndyaXRlciJdLCJyZXNvdXJjZXMiOlsiKjokVVNFUl9JRCQ6KiJdfSx7ImlkIjoibWV0YWFwaS1ycGMtYXBpIiwibWV0aG9kcyI6WyJtZXRhYXBpLWFwaTp3czpwdWJsaWM6KjoqIl0sInJvbGVzIjpbInJlYWRlciIsIndyaXRlciJdLCJyZXNvdXJjZXMiOlsiKjokVVNFUl9JRCQ6KiJdfSx7ImlkIjoibWV0YWFwaS1yZWFsLXRpbWUtc3RyZWFtaW5nLWFwaSIsIm1ldGhvZHMiOlsibWV0YWFwaS1hcGk6d3M6cHVibGljOio6KiJdLCJyb2xlcyI6WyJyZWFkZXIiLCJ3cml0ZXIiXSwicmVzb3VyY2VzIjpbIio6JFVTRVJfSUQkOioiXX0seyJpZCI6Im1ldGFzdGF0cy1hcGkiLCJtZXRob2RzIjpbIm1ldGFzdGF0cy1hcGk6cmVzdDpwdWJsaWM6KjoqIl0sInJvbGVzIjpbInJlYWRlciJdLCJyZXNvdXJjZXMiOlsiKjokVVNFUl9JRCQ6KiJdfSx7ImlkIjoicmlzay1tYW5hZ2VtZW50LWFwaSIsIm1ldGhvZHMiOlsicmlzay1tYW5hZ2VtZW50LWFwaTpyZXN0OnB1YmxpYzoqOioiXSwicm9sZXMiOlsicmVhZGVyIiwid3JpdGVyIl0sInJlc291cmNlcyI6WyIqOiRVU0VSX0lEJDoqIl19LHsiaWQiOiJtdC1tYW5hZ2VyLWFwaSIsIm1ldGhvZHMiOlsibXQtbWFuYWdlci1hcGk6cmVzdDpkZWFsaW5nOio6KiIsIm10LW1hbmFnZXItYXBpOnJlc3Q6cHVibGljOio6KiJdLCJyb2xlcyI6WyJyZWFkZXIiLCJ3cml0ZXIiXSwicmVzb3VyY2VzIjpbIio6JFVTRVJfSUQkOioiXX0seyJpZCI6ImJpbGxpbmctYXBpIiwibWV0aG9kcyI6WyJiaWxsaW5nLWFwaTpyZXN0OnB1YmxpYzoqOioiXSwicm9sZXMiOlsicmVhZGVyIl0sInJlc291cmNlcyI6WyIqOiRVU0VSX0lEJDoqIl19XSwidG9rZW5JZCI6IjIwMjEwMjEzIiwiaW1wZXJzb25hdGVkIjpmYWxzZSwicmVhbFVzZXJJZCI6IjYzNmM3Y2I3ODA2YjExYzI0NTkxZDdhMTgyZmY5ZjY4IiwiaWF0IjoxNzE2MjE3ODcwLCJleHAiOjE3MjM5OTM4NzB9.h8O0r_-FxYlqNp9rHF44VfN-BGwh9bXyBc7iNj1RTwi0QeVE9WN6IhpBTcUmA09y-VZ_YrAIvwk-zhrUI3X5EY9mZcGY37bmAJPOoFmNRolI6pme5XKKqjb00W3Km6uxFXXFq9Pjbxhk27D6r8AZeubbovI3rGUZZlQWgbVEqUAMHCZyPA2NmxtxKKoOVGKB4SBb2pBMiO45DFZaNN1b4Durt5HOU-my3i4ucQb1xvfQcu_ZTMeYZCP-FPd02svm0h_OpiBL-P4LCXH_-vFYHlhnv9fuuHV5Tjqj3p6KDHE5_92JgR8pVYPp1bjS6Ei5BOflPQriW03gkfoEjJlKtPJ_c2OUXqDyTAiITZMpMJi2K7Uew7cpBCPV6pL--t1At6tgMTzG3r8jBMCMyWvUk50889RPE4EQUztBJjudxAzoayBdIx9rYJgGuoHQwZSJawuF-Vm3CEO7KUzh5dFkG2PeyfZ9t9UlYj474Q-srz5PPI5FhmAJDx3_4wR-2X1huddDenU9hByutd9U70jClYwJcmz6YQJ1zrB0M9Bu5zQ5XFQMmiT-bwri0cQopE28DBlalWRYgYBGEO6O6nWQFbMU5cD2pvdZ2xAL9fki_eVAwbn6yQQniHfxEGVZiWsABVEuhkl0khnp8n-k0FN3RdqPo5L38d4D6eGLFaLEuRY'
ACCOUNT_ID = 'e97d4e1f-6ee9-46da-b933-91c4c6343d80'


async def main():
    api = MetaApi(token=META_API_TOKEN)
    account = await api.metatrader_account_api.get_account(account_id=ACCOUNT_ID)
    connection = account.get_streaming_connection()
    await connection.connect()

    # access local copy of terminal state
    terminal_state = connection.terminal_state

    # wait until synchronization completed
    await connection.wait_synchronized()
    ###

    # now add the listener
    listener = BitcoinSyncListener(MetatraderSymbolPriceManager("test.json"))
    connection.add_synchronization_listener(listener=listener)

    # open the connection after adding listeners
    await connection.connect()

    # first, subscribe to market data
    await connection.subscribe_to_market_data(symbol='BTCUSD')
    # print(await connection.create_market_buy_order(symbol='XAUUSD', volume=0.01))

    await asyncio.sleep(60)

    print("closing connection")
    await connection.unsubscribe_from_market_data(symbol='XAUUSD')
    connection.remove_synchronization_listener(listener)
    await connection.close()

if __name__ == '__main__':
    asyncio.run(main())
